repos:
  # Hooks that are run everywhere
  - repo: https://github.com/biomejs/pre-commit
    rev: v0.4.0
    hooks:
      - id: biome-format
        additional_dependencies: ["@biomejs/biome@1.8.3"]
  # Hooks that are run for scripts
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "2.2.1"
    hooks:
      - id: pyproject-fmt
        files: ^scripts/
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: ^scripts/
      - id: ruff-format
        files: ^scripts/
